import "./globals.css";
import { Handlee } from "@next/font/google";

import Header from "../components/header";
import Footer from "@/components/footer";

export const handlee = Handlee({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-handlee",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={handlee.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
